title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true

collections:
  projects:
    output: true


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-tsc